ALTER TABLE `akpgroup`.`attendance` 
CHANGE COLUMN `TYPE` `TYPE` SET('CHECK-IN', 'CHECK-OUT', 'TEMP-OUT', 'TEMP-IN') NULL DEFAULT NULL ;

ALTER TABLE `akpgroup`.`project` 
CHANGE COLUMN `PROGRESS` `PROGRESS` VARCHAR(100) NOT NULL ;

alter table site change PROGRESS PROGRESS VARCHAR(100) NULL;
